### ISSUE TITLE
Using TypeScript imports instead of CommonJS for Express app 

### ISSUE THREAD

**Issue by CamilleAbella** [Limerio/MusicStreaming#1]
# Using TypeScript imports instead of CommonJS for Express app 

## Issue
You can use Express as TypeScript instead of the following CommonJS require:
https://github.com/Limerio/MusicStreaming/blob/ae34620363a09dd5c0e0bf5a9370d4327de2360f/src/backend/routes/music.ts#L6

This choice will make possible the automatic typage of the request and the response, at here: (instead of `any`)
https://github.com/Limerio/MusicStreaming/blob/ae34620363a09dd5c0e0bf5a9370d4327de2360f/src/backend/routes/music.ts#L12

## To fix that

1. `npm i -D @types/express`
2. `import express from "express"`

## Annexes / Examples

- My Express project in TypeScript: https://github.com/CamilleAbella/just-a-forum

**Comment by Limerio** [comment]
Bug fixed thank you ! 😁
